name: CI
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        
    # react项目为npm run-script build，vue项目改为npm run build
    - name: Install and Build
      env:
        process.env.CI : false
      run: |
        npm install
        npm install braft-editor
        npm install antd
        npm install bootstrap@3
        npm install react-chat-elements
        npm install react-router-dom
        npm run-script build
     
    # react项目的FOLDER为build，vue项目改为dist   
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
